"""Evaluate the moderation cascade against the labelled set.

    python scripts/evaluate.py

Downloads ~3 GB of model weights on first run. Writes results/metrics.json and
results/metrics.md.
"""

from __future__ import annotations

import json
import logging
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from moderation import evaluation, labels  # noqa: E402
from moderation.config import settings  # noqa: E402
from moderation.pipeline import ModerationPipeline  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
logger = logging.getLogger("evaluate")

RESULTS = ROOT / "results"


def evaluate_stage_one_only(pipeline, examples) -> list[str]:
    """Ablation: what does the dialect model alone predict?

    This is the comparison that justifies the second stage. Without it, the
    cascade's score is a number with nothing to be measured against.
    """
    predictions = []
    for example in examples:
        raw = pipeline.hate_clf(example.text)[0]
        predictions.append(labels.normalise(raw["label"]))
    return predictions


def main() -> None:
    RESULTS.mkdir(exist_ok=True)
    examples = evaluation.load_eval_set(ROOT / "data" / "eval_set.json")
    logger.info("Loaded %d labelled examples", len(examples))

    pipeline = ModerationPipeline()

    started = time.perf_counter()
    verdicts = pipeline.moderate_batch([e.text for e in examples])
    elapsed = time.perf_counter() - started
    cascade_predictions = [v.category for v in verdicts]

    logger.info("Running stage-1-only ablation")
    stage_one_predictions = evaluate_stage_one_only(pipeline, examples)

    report = {
        "eval_set": {
            "examples": len(examples),
            "label_distribution": {
                category: sum(1 for e in examples if e.label == category)
                for category in labels.CATEGORIES
                if any(e.label == category for e in examples)
            },
        },
        "config": {
            "hate_model": settings.hate_model,
            "toxicity_model": settings.toxicity_model,
            "neutral_confidence_floor": settings.neutral_confidence_floor,
            "toxicity_threshold": settings.toxicity_threshold,
        },
        "timing": {
            "total_seconds": round(elapsed, 2),
            "seconds_per_example": round(elapsed / len(examples), 4),
        },
        "stage_one_only": {
            "binary": evaluation.score_binary(examples, stage_one_predictions).as_dict(),
            "multiclass": evaluation.score_multiclass(examples, stage_one_predictions),
        },
        "full_cascade": {
            "binary": evaluation.score_binary(examples, cascade_predictions).as_dict(),
            "multiclass": evaluation.score_multiclass(examples, cascade_predictions),
        },
        "escalations": sum(1 for v in verdicts if v.escalated),
        "actions": {
            action: sum(1 for v in verdicts if v.action == action)
            for action in ("allow", "flag", "mask")
        },
        "errors": evaluation.confusion_pairs(examples, cascade_predictions),
        "predictions": [
            {**v.as_dict(), "expected": e.label}
            for v, e in zip(verdicts, examples)
        ],
    }

    (RESULTS / "metrics.json").write_text(
        json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    write_markdown(report)

    binary = report["full_cascade"]["binary"]
    logger.info(
        "Cascade  binary acc=%.3f  P=%.3f  R=%.3f  F1=%.3f | multiclass acc=%.3f",
        binary["accuracy"], binary["precision"], binary["recall"], binary["f1"],
        report["full_cascade"]["multiclass"]["accuracy"],
    )
    stage_one_binary = report["stage_one_only"]["binary"]
    logger.info(
        "Stage 1  binary acc=%.3f  P=%.3f  R=%.3f  F1=%.3f | multiclass acc=%.3f",
        stage_one_binary["accuracy"], stage_one_binary["precision"],
        stage_one_binary["recall"], stage_one_binary["f1"],
        report["stage_one_only"]["multiclass"]["accuracy"],
    )
    logger.info("Wrote results to %s", RESULTS)


def write_markdown(report: dict) -> None:
    lines = [
        "# Evaluation results", "",
        "_Generated by `scripts/evaluate.py`._", "",
        f"Evaluated on **{report['eval_set']['examples']} hand-labelled "
        "Egyptian-dialect Arabic examples**.", "",
        "## Binary (harmful vs neutral)", "",
        "| Configuration | Accuracy | Precision | Recall | F1 |",
        "|---|---:|---:|---:|---:|",
    ]
    for key, name in (("stage_one_only", "Stage 1 only (MARBERTv2)"),
                      ("full_cascade", "Full cascade (+ toxicity stage)")):
        b = report[key]["binary"]
        lines.append(
            f"| {name} | {b['accuracy']:.3f} | {b['precision']:.3f} | "
            f"{b['recall']:.3f} | {b['f1']:.3f} |"
        )

    lines += ["", "## Multi-class (6 categories)", "",
              "| Configuration | Accuracy | Macro F1 |", "|---|---:|---:|"]
    for key, name in (("stage_one_only", "Stage 1 only (MARBERTv2)"),
                      ("full_cascade", "Full cascade (+ toxicity stage)")):
        m = report[key]["multiclass"]
        lines.append(f"| {name} | {m['accuracy']:.3f} | {m['macro_f1']:.3f} |")

    lines += ["", "## Per-category (full cascade)", "",
              "| Category | Precision | Recall | F1 | Support |",
              "|---|---:|---:|---:|---:|"]
    for category, stats in report["full_cascade"]["multiclass"]["per_category"].items():
        lines.append(
            f"| {category} | {stats['precision']:.3f} | {stats['recall']:.3f} | "
            f"{stats['f1']:.3f} | {stats['support']} |"
        )

    lines += ["", "## Errors", "",
              "| Text | Expected | Predicted |", "|---|---|---|"]
    for error in report["errors"]:
        text = error["text"].replace("|", "\\|")
        lines.append(f"| {text} | {error['expected']} | {error['predicted']} |")

    lines += ["", "## Throughput", "",
              f"- {report['timing']['seconds_per_example']:.3f} s/example on CPU",
              f"- {report['timing']['total_seconds']:.1f} s total", ""]

    (RESULTS / "metrics.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
